# Generated by Django 6.0.6 on 2026-07-12 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Supplier',
            new_name='supplier',
        ),
    ]
